### ISSUE TITLE
Release new version to bintray

### ISSUE THREAD

**Issue by chrahunt** [bincrafters/conan-boost-beast#2]
Currently the latest version available in bintray is `20171013:stable`. Attempting to use this version leads to the following error with Conan 0.29.1:

**What happens**

When attempting to install bincrafters/Boost.Beast, the following exception is raised:

```
ERROR: Unable to load conanfile in /home/chris/.conan/data/Boost.Beast/20171013/bincrafters/stable/export/conanfile.py
ValueError: not enough values to unpack (expected 4, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/python-envs/conan/lib/python3.5/site-packages/conans/client/command.py", line 309, in install
    reference = ConanFileReference.loads(args.path)
  File "/home/chris/python-envs/conan/lib/python3.5/site-packages/conans/model/ref.py", line 73, in loads
    "OpenCV/1.0.6@user/stable" % text)
conans.errors.ConanException: Wrong package recipe reference ..
Write something like OpenCV/1.0.6@user/stable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/python-envs/conan/lib/python3.5/site-packages/conans/client/loader_parse.py", line 65, in _parse_file
    loaded = imp.load_source(filename, conan_file_path)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/chris/.conan/data/Boost.Beast/20171013/bincrafters/stable/export/conanfile.py", line 1, in <module>
    from conans import ConanFile, tools, os
ImportError: cannot import name 'os'
```

**To reproduce**

```
mkdir bb-test
cd bb-test
python3 -m venv conan-env
. ./conan-env/bin/activate
pip install conan
cat <<EOF > conanfile.txt
[requires]
Boost.Beast/20171013@bincrafters/stable

[generators]
txt
EOF
mkdir build && cd build && conan install ..
```

**Information**

Python version: Python 3.5.2
Conan version: 0.29.1
Platform: Ubuntu 16.04.3

**Workaround**

Cloning the master branch (7de95e8 at time of writing) and locally doing `conan create self/stable` then using `Boost.Beast/124@self/stable` in the conanfile.txt works without issue.

**Comment by solvingj** [comment]
Sorry about that.  We had just made a fresh recipe on Wednesday but I failed to finish and upload it to bintray.  Please try this now and let me know if you have trouble: 
https://bintray.com/bincrafters/public-conan/Boost.Beast%3Abincrafters/124%3Atesting
 
Thank you for submitting feedback!

**Comment by chrahunt** [comment]
Tested and working with `Boost.Beast/124@bincrafters/testing`. :+1: Feel free to close now or when transitioned to `stable`.

**Comment by solvingj** [comment]
Great!  Will be transitioned to stable when 1.66.0 is released.
